jira:
    url: ""
    username: ""
    token: ${JIRA_API_TOKEN}
    project: ""
    epic_link_field: customfield_10014
ai:
    provider: openai
    api_key: ${OPENAI_API_KEY}
    model: gpt-4
    max_tokens: 1000
app:
    data_dir: /home/andrei/.local/share/jit
    default_editor: vim
    review_before_create: true 